// Generates src/server/generated/prompts.ts from src/prompts/*.md so the
// Cloudflare Worker bundle can ship prompts inline (Workers have no fs).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const promptsDir = resolve(root, "src", "prompts");
const outDir = resolve(root, "src", "server", "generated");
const outFile = resolve(outDir, "prompts.ts");

const findSources = readFileSync(resolve(promptsDir, "find_sources.md"), "utf8");
const verifySource = readFileSync(resolve(promptsDir, "verify_source.md"), "utf8");

const content = `// AUTO-GENERATED by scripts/inline-prompts.mjs. Do not edit by hand.
// Run \`npm run inline:prompts\` after editing src/prompts/*.md.
/* eslint-disable */
export const findSources: string = ${JSON.stringify(findSources)};
export const verifySource: string = ${JSON.stringify(verifySource)};
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, content);
console.log(`wrote ${outFile} (${content.length} bytes)`);
